### ISSUE TITLE
Nozzle digs into bed after board install

### ISSUE THREAD

**Issue by sternrulez** [bigtreetech/BIGTREETECH-SKR-CR6#6]
I installed the latest firmware yesterday, and when I attempt a print, auto level  or homing the printer, the nozzle continually tries to dig into the bed. I tried adjusting the pot under the fan shroud,  but it appears the board ignores when contact is detected. Also,regarding the auto level, my original touch screen hangs up on spot #1 - only rebooting the printer fixes it.

**Comment by KawaKode** [comment]
Hello,
I have the exact same issue and I'm on the latest firmware at the time of writing. 
Thanks in advance !

**Comment by sternrulez** [comment]
> Hello,
> I have the exact same issue and I'm on the latest firmware at the time of writing.
> Thanks in advance !

Actually I figured out the issue myself - it ended up being mostly my own fault for not paying attention what the board's ports are labeled. On the original board I believe the ports are different, so I had the z axis cable plugged into a fan port. Just to be on the safe side I did a G92 Z0 terminal command via octoprint to set the actual z0 location then M500 to save it to EEPROM. Not sure it was necessary but it's working fine now - hope that helps. If not, I'm leaving this open just in case you're still experiencing the issue after you check your ports - good luck!

**Comment by KawaKode** [comment]
Oh nice, I'll check that right now !

**Comment by KawaKode** [comment]
IT WAS EXACTLY THAT ! Thanks man !

**Comment by sternrulez** [comment]
> IT WAS EXACTLY THAT ! Thanks man !

You're quite welcome! At least now I don't feel so foolish for doing that...if I didn't I wouldn't have been able to help you lol!

**Comment by USL5264** [comment]
I put my z-stop, strain gauge plug plugged in to the z-stop socket but I still get this issue with the nozzle driving in to the bed.

Anyone can help. I'm using community firmware 6.1
